### ISSUE TITLE
Issue while installing requirements.txt

### ISSUE THREAD

**Issue by sindhujit** [ktbyers/pynet#19]
I am getting an error while installing packages from requirements.txt. The package I am having issue with is black.
```Collecting black==18.6b4
  Downloading https://ci-repo.aexp.com/repository/python-proxy-internal/packages/2d/43/64205493cfb4c8e1720208d73502a121ace2a195cd4d1d49bd7470e4fd92/black-18.6b4.tar.gz (141kB)
    100% |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 143kB 1.8MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-LVunnl/black/setup.py", line 13
        def get_long_description() -> str:
                                   ^
    SyntaxError: invalid syntax```

Any help is appreciated. Thanks!!

**Comment by ktbyers** [comment]
Black requires Python3.6 to execute.
